spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:/postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: tutmotsis69@gmail.com
    password: mibitvrtarzjbzpw
    properties:
      mail:
        smtp:
         starttls:
           enable: true